spring:
  application:
    name: waguwagu-rider
  datasource:
    url: jdbc:postgresql://localhost:5432/waguwagu?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: redis-stack
    port: 6379
