spring:
  application:
    name: waguwagu-rider
  datasource:
    url: jdbc:postgresql://waguwagu-rider-postgres:5432/rider?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${POSTGRES-USER}
    password: ${POSTGRES-PASSWORD}
  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: waguwagu-rider-redis
      port: 6379
  kafka:
    bootstrap-servers: 104.197.138.114:9094
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: prod
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
management:
  endpoints:
    web:
      exposure:
        include: "*"